---
  - name: Manage all basic packages
    hosts: all
    become: true
    tasks:
      - name: Update apt packages
        apt:
          update_cache: yes
          cache_valid_time: 86400 #One day
      - name: install apt basic packages
        apt:
          name: "{{ packages }}"
        vars:
          packages:
            - git
            - unzip
            - vim
            - nginx
            - python3-pip
            - libfontconfig1
      - name: Install pip basic packages
        pip:
          name:
            - influxdb
      - name: Install influxdb .deb package
        apt:
          deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.0_amd64.deb
      - name: Install chronograf .deb package
        apt:
          deb: https://dl.influxdata.com/chronograf/releases/chronograf_1.8.4_amd64.deb
      - name: Install grafana .deb package
        apt:
          deb: https://dl.grafana.com/oss/release/grafana_6.7.3_amd64.deb

